# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e02fada63e6cbcf85f36e18ff84a06c32e6057fd17a4918688655059c9fcc9092100626181721a504b65b6b4c9bb174e266556893b2a9d9fb93afcdabcc7171

test:
  secret_key_base: fa8405be352f4e9288979069cd8dbb611c9bf29ce34d58ece506e3f0e3067391f3afdf35bae104ed2a3441c20f7a88f9cc33c9861bb474dcdc8a9d2d99b41d95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
